version: '3.9'

services:
  frontend:
    image: hemilabs/frontend:${FRONTEND_DOCKER_TAG:-main}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
