name: Blockscout Explorer Deployment

on: 
    workflow_dispatch:

jobs:
    blockscout_build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

            - name: Deploy via docker-compose and ssh
              uses: appleboy/ssh-action@8743aa11bfbda97acb45c151ae7a2e0b203f1914 # master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                    cd ~/blockscout/docker-compose
                    docker compose down --remove-orphans
                    if [ -d ~/blockscout ]; then
                        TIMESTAMP=$(date +%Y%m%d%H%M%S)
                        sudo tar -czvf ~/backup/blockscout_$TIMESTAMP.tar.gz ~/blockscout
                    fi
                    cd ~/blockscout
                    git pull
                    cd ~/blockscout/docker-compose
                    docker compose up -d
