name: Hemi Publish Docker image

on:
  workflow_run:
    workflows:
      - Blockscout
    types:
      - completed
    branches:
      - production-hemi
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: 6.9.0
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup repo
        uses: ./.github/actions/setup-repo
        id: setup
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_TOKEN }}
          docker-remote-multi-platform: ''
      - name: Build and push Docker image (indexer + API)
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: hemilabs/blockscout:${{ env.RELEASE_VERSION }}-postrelease-${{ env.SHORT_SHA }}
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
          build-args: |
            ADMIN_PANEL_ENABLED=false
            API_V1_READ_METHODS_DISABLED=false
            API_V1_WRITE_METHODS_DISABLED=false
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}.+commit.${{ env.SHORT_SHA }}
            CHAIN_TYPE=optimism
            DISABLE_WEBAPP=false
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          provenance: true
          sbom: true
